baseURL = 'http://fossinating.com/'
theme = ["fossitheme"]
defaultContentLanguage = 'en'
paginate = 3

[params]
  socials = [{site = "twitter", link = "https://twitter.com/fossinating_", username = "fossinating_"}, {site = "github", link = "https://github.com/fossinating", username = "fossinating"}]

[Taxonomies]
  tag = 'tags'


[languages]
    [languages.en]
        contentDir = "content/en"
        title = "Fossinating"
        weight = 1


summaryLength=20